/****************************************************************************
 * boards/arm/s32k1xx/rddrone-bms772/src/s32k1xx_nrstcheck.c
 *
 *   Copyright (C) 2019 Gregory Nutt. All rights reserved.
 *   Author: Gregory Nutt <gnutt@nuttx.org>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name NuttX nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include <nuttx/arch.h>
#include <nuttx/board.h>
#include <nuttx/fs/procfs.h>
#include <nuttx/fs/dirent.h>
#include <nuttx/kmalloc.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdint.h>
#include <assert.h>
#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <debug.h>
#include <sys/mount.h>
#include <syslog.h>

#include "rddrone-bms772.h"
#include "s32k1xx_pin.h"

#include "arm_arch.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Determines the size of an intermediate buffer that must be large enough
 * to handle the longest line generated by this logic.
 */
#define NRSTCHECK_LINELEN 2

/****************************************************************************
 * Private Types
 ****************************************************************************/

/* This structure describes one open "file" */

struct nrstcheck_file_s
{
  struct procfs_file_s  base;        /* Base open file structure */
  unsigned int linesize;             /* Number of valid characters in line[] */
  char line[NRSTCHECK_LINELEN];      /* Pre-allocated buffer for formatted lines */
  bool nrstcheck;                    /* Variable representing value if the NRST line is OK */
};

static bool g_nrst_check = false;

#if defined(CONFIG_NRST_CHECK_PROC_FS) && defined(CONFIG_FS_PROCFS)

/****************************************************************************
 * Private Function Prototypes
 ****************************************************************************/

/* File system methods */

static int     nrstcheck_open(FAR struct file *filep,
                FAR const char *relpath, int oflags, mode_t mode);
static int     nrstcheck_close(FAR struct file *filep);
static ssize_t nrstcheck_read(FAR struct file *filep, FAR char *buffer,
                 size_t buflen);

static int     nrstcheck_dup(FAR const struct file *oldp,
                 FAR struct file *newp);

static int     nrstcheck_stat(FAR const char *relpath, FAR struct stat *buf);

/****************************************************************************
 * Public Data
 ****************************************************************************/

const struct procfs_operations nrstcheck_operations =
{
  nrstcheck_open,   /* open */
  nrstcheck_close,  /* close */
  nrstcheck_read,   /* read */
  NULL,             /* write */

  nrstcheck_dup,    /* dup */

  NULL,             /* opendir */
  NULL,             /* closedir */
  NULL,             /* readdir */
  NULL,             /* rewinddir */

  nrstcheck_stat    /* stat */
};

static const struct procfs_entry_s g_nrstcheck_procfs =
{
  "nrstcheck", &nrstcheck_operations
};

/****************************************************************************
 * Private Functions
 ****************************************************************************/

/****************************************************************************
 * Name: nrstcheck_open
 ****************************************************************************/

static int nrstcheck_open(FAR struct file *filep, FAR const char *relpath,
                      int oflags, mode_t mode)
{
  FAR struct nrstcheck_file_s *attr;

  finfo("Open '%s'\n", relpath);

  /* PROCFS is read-only.  Any attempt to open with any kind of write
   * access is not permitted.
   *
   * REVISIT:  Write-able proc files could be quite useful.
   */

  if ((oflags & O_WRONLY) != 0 || (oflags & O_RDONLY) == 0)
    {
      ferr("ERROR: Only O_RDONLY supported\n");
      return -EACCES;
    }

  /* "nrstcheck" is the only acceptable value for the relpath */

  if (strcmp(relpath, "nrstcheck") != 0)
    {
      ferr("ERROR: relpath is '%s'\n", relpath);
      return -ENOENT;
    }

  /* Allocate a container to hold the file attributes */

  attr = kmm_zalloc(sizeof(struct nrstcheck_file_s));
  if (!attr)
    {
      ferr("ERROR: Failed to allocate file attributes\n");
      return -ENOMEM;
    }

  /* Save the attributes as the open-specific state in filep->f_priv */

  filep->f_priv = (FAR void *)attr;
  return OK;
}

/****************************************************************************
 * Name: nrstcheck_close
 ****************************************************************************/

static int nrstcheck_close(FAR struct file *filep)
{
  FAR struct nrstcheck_file_s *attr;

  /* Recover our private data from the struct file instance */

  attr = (FAR struct nrstcheck_file_s *)filep->f_priv;
  DEBUGASSERT(attr);

  /* Release the file attributes structure */

  kmm_free(attr);
  filep->f_priv = NULL;
  return OK;
}

/****************************************************************************
 * Name: nrstcheck_read
 ****************************************************************************/

static ssize_t nrstcheck_read(FAR struct file *filep, FAR char *buffer,
                           size_t buflen)
{
  FAR struct nrstcheck_file_s *attr;
  size_t linesize;
  ssize_t ret;

  finfo("buffer=%p buflen=%d\n", buffer, (int)buflen);

  /* Recover our private data from the struct file instance */

  attr = (FAR struct nrstcheck_file_s *)filep->f_priv;
  DEBUGASSERT(attr);

  /* Get the nrstcheck value and store it */

  attr->nrstcheck = g_nrst_check;

  /* Convert the nrstcheck to a string */

  linesize  = snprintf(attr->line, NRSTCHECK_LINELEN, "%d", attr->nrstcheck);

  /* Save the linesize in case we are re-entered with f_pos > 0 */

  attr->linesize = linesize;

  /* Transfer the system reset cause to user receive buffer */

  ret = procfs_memcpy(attr->line, attr->linesize, buffer, buflen,
    &filep->f_pos);

  return ret;
}

/****************************************************************************
 * Name: nrstcheck_dup
 *
 * Description:
 *   Duplicate open file data in the new file structure.
 *
 ****************************************************************************/

static int nrstcheck_dup(FAR const struct file *oldp, FAR struct file *newp)
{
  FAR struct nrstcheck_file_s *oldattr;
  FAR struct nrstcheck_file_s *newattr;

  finfo("Dup %p->%p\n", oldp, newp);

  /* Recover our private data from the old struct file instance */

  oldattr = (FAR struct nrstcheck_file_s *)oldp->f_priv;
  DEBUGASSERT(oldattr);

  /* Allocate a new container to hold the task and attribute selection */

  newattr = kmm_malloc(sizeof(struct nrstcheck_file_s));
  if (!newattr)
    {
      ferr("ERROR: Failed to allocate file attributes\n");
      return -ENOMEM;
    }

  /* The copy the file attributes from the old attributes to the new */

  memcpy(newattr, oldattr, sizeof(struct nrstcheck_file_s));

  /* Save the new attributes in the new file structure */

  newp->f_priv = (FAR void *)newattr;
  return OK;
}

/****************************************************************************
 * Name: nrstcheck_stat
 *
 * Description: Return information about a file or directory
 *
 ****************************************************************************/

static int nrstcheck_stat(FAR const char *relpath, FAR struct stat *buf)
{
  /* "nrstcheck" is the only acceptable value for the relpath */

  if (strcmp(relpath, "nrstcheck") != 0)
    {
      ferr("ERROR: relpath is '%s'\n", relpath);
      return -ENOENT;
    }

  /* "nrstcheck" is the name for a read-only file */

  memset(buf, 0, sizeof(struct stat));
  buf->st_mode = S_IFREG | S_IROTH | S_IRGRP | S_IRUSR;
  return OK;
}

/****************************************************************************
 * Public Functions
 ****************************************************************************/

/****************************************************************************
 * Name: s32k1xx_nrstcheck
 *
 * Description:
 *   It will make the NRST pin a pull-down GPIO input pin and check the state
 *   This will be saved in a block device and the pin is configured as NRST.
 *
 ****************************************************************************/

int s32k1xx_nrstcheck(void)
{
  int ret = OK;

  /* Configure the NRST pin as GPIO input with pull down */

  ret |= s32k1xx_pinconfig(PIN_PTA5 | GPIO_PULLDOWN);

  /* Check if it went OK */

  if (ret == OK)
    {
      /* Check the value of the pin */

      g_nrst_check = s32k1xx_gpioread(PIN_PTA5 | GPIO_PULLDOWN);

      /* Make a nrstcheck blockdevice */

      ret |= procfs_register(&g_nrstcheck_procfs);

      /* Check if it went not OK */

      if (ret != OK)
        {
          /* Error output */

          ferr("ERROR: register of procfs went wrong: %d\n", ret);
        }
    }

  /* if it went not OK */

  else
    {
      /* Error output */

      ferr("ERROR: setting NRST as GPIO input went wrong: %d\n", ret);
    }

  /* Configure the NRST pin as GPIO input with pull up
   * (in order to not trigger the reset)
   */

  ret |= s32k1xx_pinconfig(PIN_PTA5 | GPIO_PULLUP);

  /* Check if it went not OK */

  if (ret != OK)
    {
      /* Error output */

      ferr("ERROR: setting NRST as GPIO input with pull-up went wrong: %d\n",
        ret);
    }

  /* Configure the NRST pin as NRST pin */

  ret |= s32k1xx_pinconfig(PIN_RESET);

  /* Check if it went not OK */

  if (ret != OK)
    {
      /* Error output */

      ferr("ERROR: setting NRST as NRST pin went wrong: %d\n", ret);
    }

  return ret;
}

#endif /* CONFIG_NRST_CHECK_PROC_FS && CONFIG_FS_PROCFS */
